"""
utils/report_formatter.py

Report export utilities for the DeepResearch Agent.

Provides three output formats:
  1. Structured Markdown — with citations, trust scores, and source badges
  2. HTML — styled, print-ready HTML for browser viewing
  3. PDF — via WeasyPrint, with professional typography and layout

Design:
  - to_markdown() is the primary format, used for streaming and downloads.
  - to_html() wraps the markdown in a styled template.
  - export_to_pdf() renders the HTML to PDF using WeasyPrint.
"""

from __future__ import annotations

import logging
from io import BytesIO

import markdown as md_lib  # type: ignore[import-untyped]

from agent.state import ReportOutput

logger = logging.getLogger(__name__)

# ────────────────────────── Markdown ──────────────────────────────────────────


def to_markdown(report: ReportOutput) -> str:
    """Convert a ReportOutput to a structured markdown document."""
    lines = [
        f"# {report.title}",
        "",
        "## Executive Summary",
        "",
        report.executive_summary,
        "",
        "## Key Findings",
        "",
    ]
    for i, finding in enumerate(report.key_findings, 1):
        lines.append(f"### {i}. {finding.claim}")
        lines.append(f"*Confidence: {finding.confidence}*")
        lines.append("")
        for c in finding.citations:
            lines.append(
                f"- [{c.title}]({c.source_url}) `{c.source_type}` (trust: {c.trust_score:.2f})"
            )
        lines.append("")

    if report.emerging_trends:
        lines.extend(["## Emerging Trends", ""])
        for trend in report.emerging_trends:
            lines.append(f"- {trend}")
        lines.append("")

    if report.recommended_next_steps:
        lines.extend(["## Recommended Next Steps", ""])
        for step in report.recommended_next_steps:
            lines.append(f"- {step}")
        lines.append("")

    if report.model_disagreements:
        lines.extend(["## Model Disagreements (Flagged)", ""])
        for d in report.model_disagreements:
            lines.append(f"> {d}")
        lines.append("")

    if report.contradictions:
        lines.extend(["## Contradictions Detected", ""])
        for contra in report.contradictions:
            lines.append(f"- **Claim A:** {contra.claim_a}")
            lines.append(f"  **Claim B:** {contra.claim_b}")
            lines.append(
                f"  **Resolution:** {contra.resolution} (preferred: {contra.preferred_source})"
            )
            lines.append("")

    lines.extend(["## Sources", ""])
    for c in report.sources:
        trust_label = "🟢" if c.trust_score >= 0.7 else ("🟡" if c.trust_score >= 0.4 else "🔴")
        lines.append(f"- {trust_label} [{c.title}]({c.source_url}) — {c.source_type}")

    lines.extend(
        [
            "",
            "---",
            f"*Report version {report.version} • Generated by DeepResearch Agent*",
        ]
    )

    return "\n".join(lines)


# ────────────────────────── HTML ──────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

    body {{
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
        max-width: 800px;
        margin: 2rem auto;
        padding: 0 2rem;
        color: #1a1a2e;
        line-height: 1.7;
        background: #ffffff;
    }}

    h1 {{
        color: #0e1117;
        font-size: 1.8rem;
        border-bottom: 3px solid #00C49F;
        padding-bottom: 0.6rem;
        margin-bottom: 1.5rem;
    }}
    h2 {{
        color: #16213e;
        font-size: 1.3rem;
        border-bottom: 2px solid #0f3460;
        padding-bottom: 0.4rem;
        margin-top: 2rem;
    }}
    h3 {{
        color: #1a1a2e;
        font-size: 1.1rem;
        margin-top: 1.5rem;
    }}

    a {{ color: #0088FE; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}

    code {{
        background: #f0f4f8;
        padding: 0.15em 0.4em;
        border-radius: 4px;
        font-size: 0.88em;
        color: #0f3460;
    }}

    blockquote {{
        border-left: 4px solid #FF8042;
        margin: 1rem 0;
        padding: 0.5rem 1rem;
        background: #fff8f2;
        font-style: italic;
    }}

    ul {{ padding-left: 1.2rem; }}
    li {{ margin-bottom: 0.4rem; }}

    em {{ color: #555; }}

    .trust-high {{ color: #27ae60; font-weight: 600; }}
    .trust-medium {{ color: #f39c12; }}
    .trust-low {{ color: #e74c3c; }}

    hr {{
        border: none;
        border-top: 1px solid #e0e0e0;
        margin: 2rem 0;
    }}

    .footer {{
        font-size: 0.8rem;
        color: #8B949E;
        text-align: center;
        margin-top: 3rem;
        padding-top: 1rem;
        border-top: 1px solid #e0e0e0;
    }}
</style>
</head>
<body>
{body}
<div class="footer">
    Generated by DeepResearch Agent &bull; Version {version}
</div>
</body>
</html>
"""


def to_html(report: ReportOutput) -> str:
    """Convert a ReportOutput to styled HTML."""
    md_text = to_markdown(report)
    html_body = md_lib.markdown(
        md_text,
        extensions=["tables", "fenced_code", "smarty"],
    )
    return _HTML_TEMPLATE.format(
        title=report.title,
        body=html_body,
        version=report.version,
    )


# ────────────────────────── PDF ───────────────────────────────────────────────


def export_to_pdf(report: ReportOutput) -> bytes:
    """
    Render a ReportOutput to a PDF document.

    Uses WeasyPrint for high-quality CSS-based PDF rendering.
    Returns the PDF as bytes (suitable for streaming or writing to disk).

    Raises:
        ImportError: If WeasyPrint is not installed.
        Exception:   Any rendering errors from WeasyPrint.
    """
    try:
        from weasyprint import HTML  # noqa: PLC0415
    except ImportError as exc:
        raise ImportError(
            "WeasyPrint is required for PDF export. Install it with: pip install weasyprint"
        ) from exc

    html_content = to_html(report)
    pdf_buffer = BytesIO()
    HTML(string=html_content).write_pdf(pdf_buffer)
    return pdf_buffer.getvalue()


def export_to_pdf_file(report: ReportOutput, output_path: str) -> None:
    """Render a ReportOutput to a PDF file on disk."""
    pdf_bytes = export_to_pdf(report)
    with open(output_path, "wb") as f:
        f.write(pdf_bytes)
    logger.info("PDF report written to %s (%d bytes)", output_path, len(pdf_bytes))
