[theme]
primaryColor = "#00C49F"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#E6EDF3"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
